# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Poyuhuang Azure Internal Consumption (61dcfa04-a42c-4d47-8476-9e01feda2573)'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az bicep build --file "./Create.bicep"
      Install-Module -Name Az.Resources -Scope CurrentUser -Repository PSGallery -Force
      Get-ChildItem
      Get-Content -Path "./Create.json"
      az deployment group create --resource-group some-other-res --template-file "./Create.json"